import "virtual:svg-icons-register";
import "../scss/style.scss";
import openWorld from "./openWorld";
import shops from "./shops";
import reviews from "./reviews";
import categories from "./categories";
import ticker from "./ticker";
import intro from "./intro";
import products from "./products";
import features from "./features";
import contactForm from "./contactForm";
import header from "./header";
import brand from "./brand";
import fancybox from "./fancybox";
import buy from "./buy";
import actualMaterials from "./actualMaterials";
import otherMaterials from "./otherMaterials";
import selects from "./selects";
import drivers from "./drivers";
import singleNews from "./singleNews";
import aboutFeatures from "./aboutFeatures";
import lineCatalog from "./lineCatalog";
import lineGallery from "./lineGallery";
import tabs from "./tabs";
import lineVariants from "./lineVariants";
import selectColor from "./selectColor";
import modals from "./modals";
import search from "./search";
import forms from "./forms";
import linePartner from "./linePromo";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/all";
import smoothScrolling from "./smoothScrolling";
import lineFeatures from "./lineFeatures";
import twoImagesWithTextScreen from "./twoImagesWithTextScreen";
import lineWithTextPreinstalled from "./lineWithTextPreinstalled";
import lineConnection from "./lineConnection";
import lineSpecs from "./lineSpecs";
import lineTooltip from "./lineTooltip";
import advantages from "./advantages";

gsap.registerPlugin(ScrollTrigger);

document.addEventListener("DOMContentLoaded", () => {
  header();
  smoothScrolling();
  singleNews();
  openWorld();
  shops();
  advantages();
  reviews();
  categories();
  ticker();
  intro();
  products();
  features();
  contactForm();
  lineTooltip();
  brand();
  fancybox();
  buy();
  actualMaterials();
  otherMaterials();
  selects();
  drivers();
  aboutFeatures();
  lineCatalog();
  lineGallery();
  tabs();
  lineVariants();
  selectColor();
  modals();
  search();
  forms();
  linePartner();
  lineFeatures();
  twoImagesWithTextScreen();
  lineWithTextPreinstalled();
  lineConnection();
  lineSpecs();
});

window.addEventListener("load", () => {
  document.body.classList.add("loaded");
  ScrollTrigger.refresh();
});
